using System;
using System.Collections.Generic;

#nullable disable

namespace ApiPetroarsa.Entities
{
    public partial class Vtmclh
    {
        public string Vtmclh_Nrocta { get; set; }
        public string Vtmclh_Rubr01 { get; set; }
        public string Vtmclh_Rubr03 { get; set; }
        public string Vtmclh_Rubr04 { get; set; }
        public string Vtmclh_Rubr05 { get; set; }
        public string Vtmclh_Rubr06 { get; set; }
        public string Vtmclh_Rubr07 { get; set; }
        public string Vtmclh_Rubr08 { get; set; }
        public string Vtmclh_Rubr09 { get; set; }
        public string Vtmclh_Rubr10 { get; set; }
        public string Vtmclh_Rubr02 { get; set; }
        public string Vtmclh_Nombre { get; set; }
        public string Vtmclh_Nrosub { get; set; }
        public string Vtmclh_Respon { get; set; }
        public string Vtmclh_Direcc { get; set; }
        public string Vtmclh_Numero { get; set; }
        public string Vtmclh_Dppiso { get; set; }
        public string Vtmclh_Deptos { get; set; }
        public string Vtmclh_Codfil { get; set; }
        public string Vtmclh_Codpai { get; set; }
        public string Vtmclh_Codpos { get; set; }
        public string Vtmclh_Municp { get; set; }
        public string Vtmclh_Fletes { get; set; }
        public string Vtmclh_Telefn { get; set; }
        public string Vtmclh_Nrofax { get; set; }
        public string Vtmclh_Ntelex { get; set; }
        public string Vtmclh_Cndiva { get; set; }
        public string Vtmclh_Tipdoc { get; set; }
        public string Vtmclh_Nrodoc { get; set; }
        public string Vtmclh_Vnddor { get; set; }
        public string Vtmclh_Cobrad { get; set; }
        public string Vtmclh_Jurisd { get; set; }
        public string Vtmclh_Codzon { get; set; }
        public string Vtmclh_Activd { get; set; }
        public string Vtmclh_Catego { get; set; }
        public string Vtmclh_Cndpag { get; set; }
        public string Vtmclh_Cndpre { get; set; }
        public string Vtmclh_Codcrd { get; set; }
        public string Vtmclh_Grubon { get; set; }
        public string Vtmclh_Camion { get; set; }
        public string Vtmclh_Camalt { get; set; }
        public string Vtmclh_Tracod { get; set; }
        public string Vtmclh_Direp1 { get; set; }
        public string Vtmclh_Direp2 { get; set; }
        public string Vtmclh_Direp3 { get; set; }
        public string Vtmclh_Direp4 { get; set; }
        public string Vtmclh_Direp5 { get; set; }
        public string Vtmclh_Horrec { get; set; }
        public string Vtmclh_Dirent { get; set; }
        public string Vtmclh_Paient { get; set; }
        public string Vtmclh_Codent { get; set; }
        public string Vtmclh_Jurent { get; set; }
        public string Vtmclh_Zonent { get; set; }
        public short Vtmclh_Copivt { get; set; }
        public short Vtmclh_Copifc { get; set; }
        public short Vtmclh_Copist { get; set; }
        public string Vtmclh_Textos { get; set; }
        public string Vtmclh_Tipdo1 { get; set; }
        public string Vtmclh_Nrodo1 { get; set; }
        public string Vtmclh_Tipdo2 { get; set; }
        public string Vtmclh_Nrodo2 { get; set; }
        public string Vtmclh_Tipdo3 { get; set; }
        public string Vtmclh_Nrodo3 { get; set; }
        public string Vtmclh_Tipdo4 { get; set; }
        public string Vtmclh_Nrodo4 { get; set; }
        public string Vtmclh_Tipdo5 { get; set; }
        public string Vtmclh_Nrodo5 { get; set; }
        public string Vtmclh_Direml { get; set; }
        public string Vtmclh_Segpro { get; set; }
        public string Vtmclh_Contad { get; set; }
        public string Vtmclh_Edisub { get; set; }
        public string Vtmclh_Cuenta { get; set; }
        public short? Vtmclh_Maxitm { get; set; }
        public short? Vtmclh_Difdia { get; set; }
        public DateTime? Vtmclh_Difdes { get; set; }
        public DateTime? Vtmclh_Difhas { get; set; }
        public decimal? Vtmclh_Perina { get; set; }
        public decimal? Vtmclh_Impdif { get; set; }
        public string Vtmclh_Email { get; set; }
        public string Vtmclh_Cndint { get; set; }
        public string Vtmclh_Distri { get; set; }
        public string Vtmclh_Deposi { get; set; }
        public string Vtmclh_Sector { get; set; }
        public string Vtmclh_Nrodis { get; set; }
        public string Vtmclh_Oleole { get; set; }
        public string Vtmclh_Bmpbmp { get; set; }
        public string Vtmclh_Inhibe { get; set; }
        public decimal? Vtmclh_Prmxpr { get; set; }
        public decimal? Vtmclh_Prmipr { get; set; }
        public string Vtmclh_Trafcr { get; set; }
        public string Vtmclh_Codcof { get; set; }
        public string Vtmclh_Modcpt { get; set; }
        public string Vtmclh_Tipcpt { get; set; }
        public string Vtmclh_Codcpt { get; set; }
        public string Vtmclh_Liscli { get; set; }
        public string Vtmclh_Tipopr { get; set; }
        public string Vtmclh_Codopr { get; set; }
        public string Vtmclh_Modpag { get; set; }
        public string Vtmclh_Tippag { get; set; }
        public string Vtmclh_Medpag { get; set; }
        public string Vtmclh_Lanexp { get; set; }
        public string Vtmclh_Genxml { get; set; }
        public string Vtmclh_Glndes { get; set; }
        public string Vtmclh_Codexp { get; set; }
        public string Vtmclh_Oblcon { get; set; }
        public string Vtmclh_Deptra { get; set; }
        public string Vtmclh_Sectra { get; set; }
        public string Vtmclh_Fisjur { get; set; }
        public string Vtmclh_Apell1 { get; set; }
        public string Vtmclh_Apell2 { get; set; }
        public string Vtmclh_Nomb01 { get; set; }
        public string Vtmclh_Nomb02 { get; set; }
        public string Usr_Vtmclh_Segmto { get; set; }
        public string Usr_Vtmclh_Codact { get; set; }
        public string Usr_Resppr { get; set; }
        public string Usr_Telppr { get; set; }
        public string Usr_Dircob { get; set; }
        public string Usr_Dyhrec { get; set; }
        public string Usr_Dyhcob { get; set; }
        public string Usr_Vtmclh_Rapel { get; set; }
        public string Usr_Vtmclh_Clicob { get; set; }
        public string Usr_Vtmclh_Asesor { get; set; }
        public string Usr_Vtmclh_Floplu { get; set; }
        public string Usr_Vtmclh_Fiagro { get; set; }
        public string Usr_Vtmclh_Altapr { get; set; }
        public string Usr_Vtmclh_Nooper { get; set; }
        public string Usr_Vtmclh_Conces { get; set; }
        public string Usr_Vtmclh_Precom { get; set; }
        public string Usr_Vtmclh_Prendar { get; set; }
        public string Usr_Vtmclh_Coment { get; set; }
        public string Usr_Vtmclh_Comnac { get; set; }
        public string Usr_Vtmclh_Gescob { get; set; }
        public string Usr_Vtmclh_Cluatc { get; set; }
        public DateTime? Vtmclh_Fecalt { get; set; }
        public DateTime? Vtmclh_Fecmod { get; set; }
        public string Vtmclh_Userid { get; set; }
        public string Vtmclh_Ultopr { get; set; }
        public string Vtmclh_Debaja { get; set; }
        public string Vtmclh_Hormov { get; set; }
        public string Vtmclh_Module { get; set; }
        public string Vtmclh_Oalias { get; set; }
        public string Vtmclh_Lottra { get; set; }
        public string Vtmclh_Lotrec { get; set; }
        public string Vtmclh_Lotori { get; set; }
        public string Vtmclh_Sysver { get; set; }
        public string Vtmclh_Cmpver { get; set; }
        public string Usr_Vtmclh_Deuven { get; set; }
        public string Usr_Vtmclh_Userid { get; set; }
        public string Usr_Vtmclh_Envisf { get; set; }
    }
}
